---
title: "RSVP"
format:
  html:
    toc: false
    css: styles_RSVP.css
---


REGISTRATION | RSVP

We would love for you to join us on

### Saturday, **29th August 2026** at **Chäsalp**  ·  4pm onwards
\

Please RSVP below by **July 1st, 2026**.\
We’d love it if everyone could register individually — even if you’re coming together as a couple or group — so we can get all the info we need for planning.

<div class="typeform-wrapper">
  <div data-tf-live="01KHJV0AXM3YSVHR8ZJMQXNPD7"></div>
</div>
<script src="//embed.typeform.com/next/embed.js"></script>


### Event Schedule

::: small-space
:::

**Friday, 28th August 2026**\
Welcome Drinks @Grain Pub.\
For anyone who would like to arrive a day early and enjoy some time together before the main event, we will be meeting at the [Grain Pub](https://www.grain.ch/) in Zurich (Kirche Fluntern) on Friday evening for some drinks and snacks from **6pm onwards**. Please let us know via the RSVP wether you would like to join.\

**Staturday, 29th August 2026**\
Main Event @Chäsalp. See [location](/location/location.qmd).\
*Apéro:* 4pm - 7pm\
*Dinner:* 7pm - 10pm\
*Dancing:* 10pm - open end

::: medium-space
:::

### Questions?

::: small-space
:::

Please find more information in our [FAQs](../FAQs/FAQs.html).

If you have any dietary restrictions, accessibility needs, or special requests, please include them in the notes section of your RSVP or contact us directly.

\

<div class="secondary-btn-wrapper">
<a href="/index.html" class="secondary-btn">Home</a>
</div>


<div class="secondary-btn-wrapper">
<a href="/location/location.html" class="secondary-btn">Location</a>
<a href="/FAQs/FAQs.html" class="secondary-btn">FAQs</a>
</div>

