---
title: "Info"
format:
  html:
    toc: false
    css: styles_info.css
---

<div class="secondary-btn-wrapper">
  <a href="/RSVP/RSVP.html" class="secondary-btn">RSVP · AN/ ABMELDUNG</a>
</div>
<div class="secondary-btn-wrapper">
  <a href="/index.html" class="secondary-btn">HOME</a>
  <a href="/info/info.html" class="secondary-btn secondary-btn--active">INFO</a>
</div>

::: small-space
:::

Find all party details below. If you’re missing anything, please contact Nadja (Janneke’s maid of honor) or Dalia (Sereina’s maid of honor), find contacts below.

Jump to a topic:

- [Event Details](#event-details)
- [Location & Transportation](#location)
- [RSVP & Guest Information](#guest-info)
- [Dress Code](#dress-code)
- [Gifts](#gifts)
- [Acommodation](#acommodation)
- [Music Wish?](#music-wish)
- [Contact](#contact)

::: medium-space
:::

---

::: {.faq-section}

## Event Details {#event-details}

::: small-space
:::

**Staturday, 29th August 2026**\
Main Event @[Chäsalp](https://www.chaesalp.ch), Zürich.\
*4pm onwards* · Welcome Drinks \
*7pm - 10pm* · Dinner \
*10pm - open end* · Dancing 

**Friday, 28th August 2026**\
Welcome Drinks @[Grain Pub](https://www.grain.ch/), Zürich Fluntern.\
Join us for a relaxed get-together the evening before!
We’ll meet at the Grain Pub on Friday evening from **6pm** onwards for drinks and snacks. Let us know via [RSVP](/RSVP/RSVP.qmd) if you’d like to join.\



:::


::: {.faq-section}

## Location & Transportation {#location}

::: small-space
:::


**Location**\
Chäsalp | Restaurant Alter Tobelhof\
Tobelhofstrasse 236, 8044 Zürich\
[www.chaesalp.ch](https://www.chaesalp.ch)


**By Car**\
There is free parking available at Chäsalp.\
Time from Zürich city: *15 min.*\


**By Public Transport**\
Bus stop "Zürich Tobelhof".\
Check the [SBB Journey Planner](https://www.sbb.ch/de?stops=Z%C3%BCrich+HB_I8503000~Z%C3%BCrich,+Tobelhof_I8591396).\
Time from Zürich city: *30 min.*\

Connections run all night back from Chäsalp (Tobelhof) to Zürich city. We're also happy to help with a taxi or Uber.

::: medium-space
:::

<iframe 
  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2700.547!2d8.587921!3d47.3820486!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479aa0f272036387%3A0x7729e11af3c7904f!2sCh%C3%A4salp!5e0!3m2!1sen!2sch!4v1234567890" 
  width="100%" 
  height="400" 
  style="border:0;" 
  allowfullscreen="" 
  loading="lazy" 
  referrerpolicy="no-referrer-when-downgrade">
</iframe>

:::

---

::: {.faq-section}

## RSVP & Guest Information {#guest-info}

::: small-space
:::

Please [RSVP (An/ Abmelden)](/RSVP/RSVP.qmd) latest by **May 31st, 2026**, even if you are unable to attend. This is important to us for further planning.

**Can I bring a plus-one?**\
We've carefully curated the guest list based on the venue capacity. If your invitation includes "and guest" or names a specific person, they are warmly welcomed. If you're unsure, please contact us!

**Are children welcome?**\
We love your little ones, but we've decided to make this event an adults-only celebration. 

:::




::: {.faq-section}

## Dress Code {#dress-code}

::: small-space
:::

**What should I wear?**\
Whatever makes you feel "happy and pretty and gaaay"!

Late August in Zürich is usually around 20°C. Maybe bring a light jacket and some
comfy shoes (some uneven walking - maybe even some running).
The venue has indoor and outdoor space, so we’re good whatever the weather.

:::



::: {.faq-section}

## Gifts {#gifts}

::: small-space
:::

Having you celebrate with us is what matters most to us — speeches, formal contributions or gifts are neither needed nor expected.\ 

...but, for anyone who’d still like to chip in:
you can support us, and we’ll split it between a donation to [*Alzheimer Schweiz*](https://www.alzheimer-schweiz.ch/de/startseite) and our new dream bed.

At the party, you’ll find two easy ways to contribute:
a classic piggy bank 🐷 or TWINT (Swiss only).

If you prefer to sort it out in advance, feel free to transfer to:\
IBAN (Janneke van Woerden):\
CH08 0483 5172 5204 2000 0 \
Payment reference:\
"Gift Janneke & Sereina"\

Please don’t go overboard!

:::



::: {.faq-section}

## Acommodation {#acommodation}

::: small-space
:::

Looking for a place to stay?\
For accommodation recommendations, feel free to reach out to Janneke directly.

:::



::: {.faq-section}

## Music Wish? {#music-wish}

::: small-space
:::

Got a song that needs to be played at the party? Drop it here 👇!

<div style="position: relative; width: calc(100% + 4rem); overflow: hidden; padding-top: 150%; margin-left: -2rem; margin-right: -2rem;">
  <iframe 
    src="https://docs.google.com/forms/d/e/1FAIpQLSeXqR-h6Y2nda-t4tDVf3gdkayCtJBccQ4aeu06zyOmfe__Yg/viewform?embedded=true"
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;"
    marginheight="0" marginwidth="0">
    Loading…
  </iframe>
</div>

:::



::: {.faq-section}

## Contact {#contact}

For any other question you may have, please contact one or both of the two:

::: small-space
:::

**Nadja** (Janneke’s maid of honor)\
 +41 79 797 38 91

**Dalia** (Sereina’s maid of honor)\
+41 79 794 57 85
:::
